resources:
- repo: self
  clean: true
  lfs: true

phases:
- phase: Main
  variables:
    Configuration: Release
    Platform: Any CPU

  queue:
    name: Hosted macOS Preview

  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0

  - task: NuGetCommand@2
    inputs:
      solution: "GSSDKBinding.sln"

  - task: MSBuild@1
    inputs:
      solution: GSSDKBinding.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:PackageOutputPath=$(Build.ArtifactStagingDirectory) /p:GeneratePackageOnBuild=true
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: $(Build.DefinitionName)
      ArtifactType: "Container"
